name: secure_note_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^6.0.3
  share_plus: ^8.0.1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  modal_bottom_sheet: ^3.0.0
  file_picker: ^8.0.0+1
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  local_auth: ^2.1.2
  local_session_timeout: ^2.1.1
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3

                  



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
   

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
    
    - family: MerriweatherBlack
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf

    - family: NotoMonochromaticEmoji
      fonts:
        - asset: assets/fonts/NotoEmoji-VariableFont_wght.ttf
